#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlexGrid101.Resource", IsApplication=true)]

namespace FlexGrid101
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010019
			public const int alternatingRowCellBackgroundColor = 2130771993;
			
			// aapt resource value: 0x7f010022
			public const int borderColor = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int borderWidth = 2130772003;
			
			// aapt resource value: 0x7f010016
			public const int cellBackgroundColor = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int cellFontColor = 2130771991;
			
			// aapt resource value: 0x7f010005
			public const int cellFontGravity = 2130771973;
			
			// aapt resource value: 0x7f010014
			public const int cellFontSize = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int cellFontTypeface = 2130771989;
			
			// aapt resource value: 0x7f010004
			public const int cellFontWeight = 2130771972;
			
			// aapt resource value: 0x7f010013
			public const int cellPaddingBottom = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int cellPaddingLeft = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int cellPaddingRight = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cellPaddingTop = 2130771985;
			
			// aapt resource value: 0x7f01000c
			public const int columnHeaderBackgroundColor = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int columnHeaderFontColor = 2130771981;
			
			// aapt resource value: 0x7f010002
			public const int columnHeaderFontGravity = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int columnHeaderFontSize = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int columnHeaderFontTypeface = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int columnHeaderFontWeight = 2130771968;
			
			// aapt resource value: 0x7f010018
			public const int gridLinesColor = 2130771992;
			
			// aapt resource value: 0x7f010024
			public const int groupHeaderBackgroundColor = 2130772004;
			
			// aapt resource value: 0x7f010006
			public const int headerSelectedBackgroundColor = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int headerSelectedFontColor = 2130771975;
			
			// aapt resource value: 0x7f010025
			public const int ringoFlexGrid = 2130772005;
			
			// aapt resource value: 0x7f01000e
			public const int rowHeaderBackgroundColor = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int rowHeaderFontColor = 2130771983;
			
			// aapt resource value: 0x7f010003
			public const int rowHeaderFontGravity = 2130771971;
			
			// aapt resource value: 0x7f01000a
			public const int rowHeaderFontSize = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int rowHeaderFontTypeface = 2130771979;
			
			// aapt resource value: 0x7f010001
			public const int rowHeaderFontWeight = 2130771969;
			
			// aapt resource value: 0x7f010020
			public const int selectedBackgroundColor = 2130772000;
			
			// aapt resource value: 0x7f01001b
			public const int selectedCellBackgroundColor = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int selectedCellBorderColor = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int selectedCellBorderWidth = 2130771996;
			
			// aapt resource value: 0x7f010021
			public const int selectedFontColor = 2130772001;
			
			// aapt resource value: 0x7f01001e
			public const int selectionAdornerColor = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public const int selectionBackgroundColor = 2130771997;
			
			// aapt resource value: 0x7f01001f
			public const int selectionFontColor = 2130771999;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int defaultAlternatingRowCellBackgroundColor = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int defaultBorderColor = 2130968588;
			
			// aapt resource value: 0x7f040006
			public const int defaultCellBackgroundColor = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int defaultCellFontColor = 2130968583;
			
			// aapt resource value: 0x7f04000b
			public const int defaultGroupHeaderBackgroundColor = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int defaultHeaderBackgroundColor = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int defaultHeaderFontColor = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int defaultHeaderSelectedBackgroundColor = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int defaultHeaderSelectedFontColor = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int defaultSelectedCellBackgroundColor = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int defaultSelectedCellBorderColor = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int filter_view_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int filter_view_text = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int defaultBorderWidth = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int defaultCellFontSize = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int defaultCellPaddingBottom = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int defaultCellPaddingLeft = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int defaultCellPaddingRight = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int defaultCellPaddingTop = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int defaultHeaderFontSize = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int defaultSelectedCellBorderWidth = 2131034120;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int flexgrid = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int BOLD = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int BOLD_ITALIC = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int BOTTOM = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int CENTER_HORIZONTAL = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int CENTER_VERTICAL = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int ITALIC = 2131296258;
			
			// aapt resource value: 0x7f090007
			public const int LEFT = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int NORMAL = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int RIGHT = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int TOP = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int listView1 = 2131296266;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080003
			public const int defaultCellFontGravity = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int defaultCellFontWeight = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int defaultHeaderFontGravity = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int defaultHeaderFontWeight = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GettingStarted = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000a
			public const int ApplicationName = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int Hello = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int defaultCellFontTypeface = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int defaultHeaderFontTypeface = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int filter_view_ascending = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int filter_view_clear = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int filter_view_descending = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int filter_view_done = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int filter_view_select_all = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int groupHeaderFormat = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Style_Ringo = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Style_Ringo_FlexGrid = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Style_Ringo_FlexGrid_Default = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int Theme_Ringo_FlexGrid_Default = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlexGrid = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 25
			public const int FlexGrid_alternatingRowCellBackgroundColor = 25;
			
			// aapt resource value: 34
			public const int FlexGrid_borderColor = 34;
			
			// aapt resource value: 35
			public const int FlexGrid_borderWidth = 35;
			
			// aapt resource value: 22
			public const int FlexGrid_cellBackgroundColor = 22;
			
			// aapt resource value: 23
			public const int FlexGrid_cellFontColor = 23;
			
			// aapt resource value: 5
			public const int FlexGrid_cellFontGravity = 5;
			
			// aapt resource value: 20
			public const int FlexGrid_cellFontSize = 20;
			
			// aapt resource value: 21
			public const int FlexGrid_cellFontTypeface = 21;
			
			// aapt resource value: 4
			public const int FlexGrid_cellFontWeight = 4;
			
			// aapt resource value: 19
			public const int FlexGrid_cellPaddingBottom = 19;
			
			// aapt resource value: 16
			public const int FlexGrid_cellPaddingLeft = 16;
			
			// aapt resource value: 18
			public const int FlexGrid_cellPaddingRight = 18;
			
			// aapt resource value: 17
			public const int FlexGrid_cellPaddingTop = 17;
			
			// aapt resource value: 12
			public const int FlexGrid_columnHeaderBackgroundColor = 12;
			
			// aapt resource value: 13
			public const int FlexGrid_columnHeaderFontColor = 13;
			
			// aapt resource value: 2
			public const int FlexGrid_columnHeaderFontGravity = 2;
			
			// aapt resource value: 8
			public const int FlexGrid_columnHeaderFontSize = 8;
			
			// aapt resource value: 9
			public const int FlexGrid_columnHeaderFontTypeface = 9;
			
			// aapt resource value: 0
			public const int FlexGrid_columnHeaderFontWeight = 0;
			
			// aapt resource value: 24
			public const int FlexGrid_gridLinesColor = 24;
			
			// aapt resource value: 36
			public const int FlexGrid_groupHeaderBackgroundColor = 36;
			
			// aapt resource value: 6
			public const int FlexGrid_headerSelectedBackgroundColor = 6;
			
			// aapt resource value: 7
			public const int FlexGrid_headerSelectedFontColor = 7;
			
			// aapt resource value: 14
			public const int FlexGrid_rowHeaderBackgroundColor = 14;
			
			// aapt resource value: 15
			public const int FlexGrid_rowHeaderFontColor = 15;
			
			// aapt resource value: 3
			public const int FlexGrid_rowHeaderFontGravity = 3;
			
			// aapt resource value: 10
			public const int FlexGrid_rowHeaderFontSize = 10;
			
			// aapt resource value: 11
			public const int FlexGrid_rowHeaderFontTypeface = 11;
			
			// aapt resource value: 1
			public const int FlexGrid_rowHeaderFontWeight = 1;
			
			// aapt resource value: 32
			public const int FlexGrid_selectedBackgroundColor = 32;
			
			// aapt resource value: 27
			public const int FlexGrid_selectedCellBackgroundColor = 27;
			
			// aapt resource value: 26
			public const int FlexGrid_selectedCellBorderColor = 26;
			
			// aapt resource value: 28
			public const int FlexGrid_selectedCellBorderWidth = 28;
			
			// aapt resource value: 33
			public const int FlexGrid_selectedFontColor = 33;
			
			// aapt resource value: 30
			public const int FlexGrid_selectionAdornerColor = 30;
			
			// aapt resource value: 29
			public const int FlexGrid_selectionBackgroundColor = 29;
			
			// aapt resource value: 31
			public const int FlexGrid_selectionFontColor = 31;
			
			public static int[] RingoFlexGridTheme = new int[] {
					2130772005};
			
			// aapt resource value: 0
			public const int RingoFlexGridTheme_ringoFlexGrid = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
