#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CalendarSample.Resource", IsApplication=true)]

namespace CalendarSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int header_slide_bottom_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int header_slide_bottom_out = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int header_slide_top_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int header_slide_top_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_bottom_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int slide_bottom_out = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int slide_top_in = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_top_out = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Cloudy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int left_black = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int left_gray = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int left_white = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int PartlyCloudy = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Rain = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int right_black = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int right_gray = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int right_white = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Storm = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Sun = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int calendar = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int calendar_item_tv_day = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int day_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] XuniCalendar;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
