#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlexChartSample.Resource", IsApplication=true)]

namespace FlexChartSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080001
			public const int flexChartCocoaPalette = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int flexChartCoralPalette = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int flexChartDarkPalette = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int flexChartDefaultFlexChartPalette = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int flexChartHighConstrastPalette = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int flexChartLightPalette = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int flexChartMidnightPalette = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int flexChartMinimalPalette = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int flexChartModernPalette = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int flexChartOrganicPalette = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int flexChartSlatePalette = 2131230730;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010057
			public const int flexChartSeries_binding = 2130772055;
			
			// aapt resource value: 0x7f010059
			public const int flexChartSeries_borderColor = 2130772057;
			
			// aapt resource value: 0x7f01005a
			public const int flexChartSeries_borderWidth = 2130772058;
			
			// aapt resource value: 0x7f010017
			public const int flexChartSeries_chartType = 2130771991;
			
			// aapt resource value: 0x7f010058
			public const int flexChartSeries_color = 2130772056;
			
			// aapt resource value: 0x7f010056
			public const int flexChartSeries_name = 2130772054;
			
			// aapt resource value: 0x7f01005c
			public const int flexChartSeries_symbolBorderColor = 2130772060;
			
			// aapt resource value: 0x7f01005d
			public const int flexChartSeries_symbolBorderWidth = 2130772061;
			
			// aapt resource value: 0x7f01005b
			public const int flexChartSeries_symbolColor = 2130772059;
			
			// aapt resource value: 0x7f010018
			public const int flexChartSeries_visibility = 2130771992;
			
			// aapt resource value: 0x7f01000a
			public const int flexChart_axisX_axisLineVisible = 2130771978;
			
			// aapt resource value: 0x7f010041
			public const int flexChart_axisX_format = 2130772033;
			
			// aapt resource value: 0x7f010031
			public const int flexChart_axisX_labelAngle = 2130772017;
			
			// aapt resource value: 0x7f01002e
			public const int flexChart_axisX_labelFontColor = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int flexChart_axisX_labelFontSize = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int flexChart_axisX_labelFontTypeface = 2130772016;
			
			// aapt resource value: 0x7f010007
			public const int flexChart_axisX_labelFontWeight = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int flexChart_axisX_labelsVisible = 2130771977;
			
			// aapt resource value: 0x7f010035
			public const int flexChart_axisX_lineColor = 2130772021;
			
			// aapt resource value: 0x7f010036
			public const int flexChart_axisX_lineWidth = 2130772022;
			
			// aapt resource value: 0x7f010037
			public const int flexChart_axisX_majorGridColor = 2130772023;
			
			// aapt resource value: 0x7f01003b
			public const int flexChart_axisX_majorGridFill = 2130772027;
			
			// aapt resource value: 0x7f01000c
			public const int flexChart_axisX_majorGridVisible = 2130771980;
			
			// aapt resource value: 0x7f010038
			public const int flexChart_axisX_majorGridWidth = 2130772024;
			
			// aapt resource value: 0x7f010039
			public const int flexChart_axisX_majorTickColor = 2130772025;
			
			// aapt resource value: 0x7f01000b
			public const int flexChart_axisX_majorTickOverlap = 2130771979;
			
			// aapt resource value: 0x7f01003a
			public const int flexChart_axisX_majorTickWidth = 2130772026;
			
			// aapt resource value: 0x7f01003c
			public const int flexChart_axisX_minorGridColor = 2130772028;
			
			// aapt resource value: 0x7f010040
			public const int flexChart_axisX_minorGridFill = 2130772032;
			
			// aapt resource value: 0x7f01000e
			public const int flexChart_axisX_minorGridVisible = 2130771982;
			
			// aapt resource value: 0x7f01003d
			public const int flexChart_axisX_minorGridWidth = 2130772029;
			
			// aapt resource value: 0x7f01003e
			public const int flexChart_axisX_minorTickColor = 2130772030;
			
			// aapt resource value: 0x7f01000d
			public const int flexChart_axisX_minorTickOverlap = 2130771981;
			
			// aapt resource value: 0x7f01003f
			public const int flexChart_axisX_minorTickWidth = 2130772031;
			
			// aapt resource value: 0x7f010032
			public const int flexChart_axisX_titleFontColor = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int flexChart_axisX_titleFontSize = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int flexChart_axisX_titleFontTypeface = 2130772020;
			
			// aapt resource value: 0x7f010008
			public const int flexChart_axisX_titleFontWeight = 2130771976;
			
			// aapt resource value: 0x7f010012
			public const int flexChart_axisY_axisLineVisible = 2130771986;
			
			// aapt resource value: 0x7f010042
			public const int flexChart_axisY_format = 2130772034;
			
			// aapt resource value: 0x7f010046
			public const int flexChart_axisY_labelAngle = 2130772038;
			
			// aapt resource value: 0x7f010043
			public const int flexChart_axisY_labelFontColor = 2130772035;
			
			// aapt resource value: 0x7f010044
			public const int flexChart_axisY_labelFontSize = 2130772036;
			
			// aapt resource value: 0x7f010045
			public const int flexChart_axisY_labelFontTypeface = 2130772037;
			
			// aapt resource value: 0x7f01000f
			public const int flexChart_axisY_labelFontWeight = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int flexChart_axisY_labelsVisible = 2130771985;
			
			// aapt resource value: 0x7f01004a
			public const int flexChart_axisY_lineColor = 2130772042;
			
			// aapt resource value: 0x7f01004b
			public const int flexChart_axisY_lineWidth = 2130772043;
			
			// aapt resource value: 0x7f01004c
			public const int flexChart_axisY_majorGridColor = 2130772044;
			
			// aapt resource value: 0x7f010050
			public const int flexChart_axisY_majorGridFill = 2130772048;
			
			// aapt resource value: 0x7f010013
			public const int flexChart_axisY_majorGridVisible = 2130771987;
			
			// aapt resource value: 0x7f01004d
			public const int flexChart_axisY_majorGridWidth = 2130772045;
			
			// aapt resource value: 0x7f01004e
			public const int flexChart_axisY_majorTickColor = 2130772046;
			
			// aapt resource value: 0x7f010014
			public const int flexChart_axisY_majorTickOverlap = 2130771988;
			
			// aapt resource value: 0x7f01004f
			public const int flexChart_axisY_majorTickWidth = 2130772047;
			
			// aapt resource value: 0x7f010051
			public const int flexChart_axisY_minorGridColor = 2130772049;
			
			// aapt resource value: 0x7f010055
			public const int flexChart_axisY_minorGridFill = 2130772053;
			
			// aapt resource value: 0x7f010015
			public const int flexChart_axisY_minorGridVisible = 2130771989;
			
			// aapt resource value: 0x7f010052
			public const int flexChart_axisY_minorGridWidth = 2130772050;
			
			// aapt resource value: 0x7f010053
			public const int flexChart_axisY_minorTickColor = 2130772051;
			
			// aapt resource value: 0x7f010016
			public const int flexChart_axisY_minorTickOverlap = 2130771990;
			
			// aapt resource value: 0x7f010054
			public const int flexChart_axisY_minorTickWidth = 2130772052;
			
			// aapt resource value: 0x7f010047
			public const int flexChart_axisY_titleFontColor = 2130772039;
			
			// aapt resource value: 0x7f010048
			public const int flexChart_axisY_titleFontSize = 2130772040;
			
			// aapt resource value: 0x7f010049
			public const int flexChart_axisY_titleFontTypeface = 2130772041;
			
			// aapt resource value: 0x7f010010
			public const int flexChart_axisY_titleFontWeight = 2130771984;
			
			// aapt resource value: 0x7f010022
			public const int flexChart_backgroundColor = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int flexChart_borderColor = 2130772003;
			
			// aapt resource value: 0x7f010024
			public const int flexChart_borderWidth = 2130772004;
			
			// aapt resource value: 0x7f010005
			public const int flexChart_chartType = 2130771973;
			
			// aapt resource value: 0x7f01001e
			public const int flexChart_footer = 2130771998;
			
			// aapt resource value: 0x7f010021
			public const int flexChart_footerFontColor = 2130772001;
			
			// aapt resource value: 0x7f010003
			public const int flexChart_footerFontGravity = 2130771971;
			
			// aapt resource value: 0x7f01001f
			public const int flexChart_footerFontSize = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int flexChart_footerFontTypeface = 2130772000;
			
			// aapt resource value: 0x7f010002
			public const int flexChart_footerFontWeight = 2130771970;
			
			// aapt resource value: 0x7f01001a
			public const int flexChart_header = 2130771994;
			
			// aapt resource value: 0x7f01001d
			public const int flexChart_headerFontColor = 2130771997;
			
			// aapt resource value: 0x7f010001
			public const int flexChart_headerFontGravity = 2130771969;
			
			// aapt resource value: 0x7f01001b
			public const int flexChart_headerFontSize = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int flexChart_headerFontTypeface = 2130771996;
			
			// aapt resource value: 0x7f010000
			public const int flexChart_headerFontWeight = 2130771968;
			
			// aapt resource value: 0x7f01002b
			public const int flexChart_legend_FontColor = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int flexChart_legend_FontSize = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int flexChart_legend_FontTypeface = 2130772013;
			
			// aapt resource value: 0x7f010004
			public const int flexChart_legend_FontWeight = 2130771972;
			
			// aapt resource value: 0x7f010028
			public const int flexChart_legend_backgroundColor = 2130772008;
			
			// aapt resource value: 0x7f010029
			public const int flexChart_legend_borderColor = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int flexChart_legend_borderWidth = 2130772010;
			
			// aapt resource value: 0x7f010019
			public const int flexChart_palette = 2130771993;
			
			// aapt resource value: 0x7f010025
			public const int flexChart_plotAreabackgroundColor = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int flexChart_selectedBorderColor = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int flexChart_selectedBorderWidth = 2130772007;
			
			// aapt resource value: 0x7f010006
			public const int flexChart_stackingType = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int defaultFlexChartAxisX_labelAngle = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int defaultFlexChartAxisX_labelFontSize = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int defaultFlexChartAxisX_lineWidth = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int defaultFlexChartAxisX_majorGridWidth = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int defaultFlexChartAxisX_majorTickWidth = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int defaultFlexChartAxisX_minorGridWidth = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int defaultFlexChartAxisX_minorTickWidth = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int defaultFlexChartAxisX_titleFontSize = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int defaultFlexChartAxisY_labelAngle = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int defaultFlexChartAxisY_labelFontSize = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int defaultFlexChartAxisY_lineWidth = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int defaultFlexChartAxisY_majorGridWidth = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int defaultFlexChartAxisY_majorTickWidth = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int defaultFlexChartAxisY_minorGridWidth = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int defaultFlexChartAxisY_minorTickWidth = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int defaultFlexChartAxisY_titleFontSize = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int defaultFlexChartBorderWidth = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int defaultFlexChartFooterFontSize = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int defaultFlexChartHeaderFontSize = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int defaultFlexChartLegend_FontSize = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int defaultFlexChartLegend_borderWidth = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int defaultFlexChartSelectedBorderWidth = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int defaultFlexChartSeriesBorderWidth = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int defaultFlexChartSeriesSymbolBorderWidth = 2131099665;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chart_area = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dct = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090007
			public const int AREA = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int BAR = 2131296264;
			
			// aapt resource value: 0x7f090000
			public const int BOLD = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int BOLD_ITALIC = 2131296257;
			
			// aapt resource value: 0x7f090009
			public const int BUBBLE = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int CANDLE = 2131296266;
			
			// aapt resource value: 0x7f090004
			public const int CENTER_HORIZONTAL = 2131296260;
			
			// aapt resource value: 0x7f09000b
			public const int COLUMN = 2131296267;
			
			// aapt resource value: 0x7f090016
			public const int FALSE = 2131296278;
			
			// aapt resource value: 0x7f09001a
			public const int HIDDEN = 2131296282;
			
			// aapt resource value: 0x7f09000c
			public const int HLOC = 2131296268;
			
			// aapt resource value: 0x7f090018
			public const int INSIDE = 2131296280;
			
			// aapt resource value: 0x7f090002
			public const int ITALIC = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int LEFT = 2131296261;
			
			// aapt resource value: 0x7f09001b
			public const int LEGEND = 2131296283;
			
			// aapt resource value: 0x7f09000d
			public const int LINE = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int LINESYMBOLS = 2131296270;
			
			// aapt resource value: 0x7f090013
			public const int NONE = 2131296275;
			
			// aapt resource value: 0x7f090003
			public const int NORMAL = 2131296259;
			
			// aapt resource value: 0x7f090019
			public const int OUTSIDE = 2131296281;
			
			// aapt resource value: 0x7f09001c
			public const int PLOT = 2131296284;
			
			// aapt resource value: 0x7f090006
			public const int RIGHT = 2131296262;
			
			// aapt resource value: 0x7f09000f
			public const int SCATTER = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int SPLINE = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int SPLINEAREA = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int SPLINESYMBOLS = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int STACKED = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int STACKED100pc = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int TRUE = 2131296279;
			
			// aapt resource value: 0x7f09001d
			public const int VISIBLE = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int flexchart = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int listView1 = 2131296287;
			
			// aapt resource value: 0x7f090021
			public const int tooltipContent = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int tooltipTitle = 2131296288;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050004
			public const int defaultFlexChartAxisX_axisLineVisible = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int defaultFlexChartAxisX_labelFontWeight = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int defaultFlexChartAxisX_labelsVisible = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int defaultFlexChartAxisX_majorGridVisible = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int defaultFlexChartAxisX_majorTickOverlap = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int defaultFlexChartAxisX_minorGridVisible = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int defaultFlexChartAxisX_minorTickOverlap = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int defaultFlexChartAxisX_titleFontWeight = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int defaultFlexChartAxisY_axisLineVisible = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int defaultFlexChartAxisY_labelFontWeight = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int defaultFlexChartAxisY_labelsVisible = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int defaultFlexChartAxisY_majorGridVisible = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int defaultFlexChartAxisY_majorTickOverlap = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int defaultFlexChartAxisY_minorGridVisible = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int defaultFlexChartAxisY_minorTickOverlap = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int defaultFlexChartAxisY_titleFontWeight = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int defaultFlexChartChartType = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int defaultFlexChartFooterFontGravity = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int defaultFlexChartFooterFontWeight = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int defaultFlexChartHeaderFontGravity = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int defaultFlexChartHeaderFontWeight = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int defaultFlexChartLegend_FontWeight = 2131034136;
			
			// aapt resource value: 0x7f050012
			public const int defaultFlexChartSeriesChartType = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int defaultFlexChartSeriesVisibility = 2131034131;
			
			// aapt resource value: 0x7f050001
			public const int defaultFlexChartStackingType = 2131034113;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GettingStarted = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int tooltip = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070008
			public const int ApplicationName = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int Hello = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int defaultFlexChartAxisX_labelFontTypeface = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int defaultFlexChartAxisX_titleFontTypeface = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int defaultFlexChartAxisY_labelFontTypeface = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int defaultFlexChartAxisY_titleFontTypeface = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int defaultFlexChartFooterFontTypeface = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int defaultFlexChartHeaderFontTypeface = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int defaultFlexChartLegend_FontTypeface = 2131165190;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int AppBaseTheme = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AppTheme = 2130968577;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlexChart = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032,
					2130772033,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041,
					2130772042,
					2130772043,
					2130772044,
					2130772045,
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052,
					2130772053};
			
			// aapt resource value: 10
			public const int FlexChart_flexChart_axisX_axisLineVisible = 10;
			
			// aapt resource value: 63
			public const int FlexChart_flexChart_axisX_format = 63;
			
			// aapt resource value: 47
			public const int FlexChart_flexChart_axisX_labelAngle = 47;
			
			// aapt resource value: 44
			public const int FlexChart_flexChart_axisX_labelFontColor = 44;
			
			// aapt resource value: 45
			public const int FlexChart_flexChart_axisX_labelFontSize = 45;
			
			// aapt resource value: 46
			public const int FlexChart_flexChart_axisX_labelFontTypeface = 46;
			
			// aapt resource value: 7
			public const int FlexChart_flexChart_axisX_labelFontWeight = 7;
			
			// aapt resource value: 9
			public const int FlexChart_flexChart_axisX_labelsVisible = 9;
			
			// aapt resource value: 51
			public const int FlexChart_flexChart_axisX_lineColor = 51;
			
			// aapt resource value: 52
			public const int FlexChart_flexChart_axisX_lineWidth = 52;
			
			// aapt resource value: 53
			public const int FlexChart_flexChart_axisX_majorGridColor = 53;
			
			// aapt resource value: 57
			public const int FlexChart_flexChart_axisX_majorGridFill = 57;
			
			// aapt resource value: 12
			public const int FlexChart_flexChart_axisX_majorGridVisible = 12;
			
			// aapt resource value: 54
			public const int FlexChart_flexChart_axisX_majorGridWidth = 54;
			
			// aapt resource value: 55
			public const int FlexChart_flexChart_axisX_majorTickColor = 55;
			
			// aapt resource value: 11
			public const int FlexChart_flexChart_axisX_majorTickOverlap = 11;
			
			// aapt resource value: 56
			public const int FlexChart_flexChart_axisX_majorTickWidth = 56;
			
			// aapt resource value: 58
			public const int FlexChart_flexChart_axisX_minorGridColor = 58;
			
			// aapt resource value: 62
			public const int FlexChart_flexChart_axisX_minorGridFill = 62;
			
			// aapt resource value: 14
			public const int FlexChart_flexChart_axisX_minorGridVisible = 14;
			
			// aapt resource value: 59
			public const int FlexChart_flexChart_axisX_minorGridWidth = 59;
			
			// aapt resource value: 60
			public const int FlexChart_flexChart_axisX_minorTickColor = 60;
			
			// aapt resource value: 13
			public const int FlexChart_flexChart_axisX_minorTickOverlap = 13;
			
			// aapt resource value: 61
			public const int FlexChart_flexChart_axisX_minorTickWidth = 61;
			
			// aapt resource value: 48
			public const int FlexChart_flexChart_axisX_titleFontColor = 48;
			
			// aapt resource value: 49
			public const int FlexChart_flexChart_axisX_titleFontSize = 49;
			
			// aapt resource value: 50
			public const int FlexChart_flexChart_axisX_titleFontTypeface = 50;
			
			// aapt resource value: 8
			public const int FlexChart_flexChart_axisX_titleFontWeight = 8;
			
			// aapt resource value: 18
			public const int FlexChart_flexChart_axisY_axisLineVisible = 18;
			
			// aapt resource value: 64
			public const int FlexChart_flexChart_axisY_format = 64;
			
			// aapt resource value: 68
			public const int FlexChart_flexChart_axisY_labelAngle = 68;
			
			// aapt resource value: 65
			public const int FlexChart_flexChart_axisY_labelFontColor = 65;
			
			// aapt resource value: 66
			public const int FlexChart_flexChart_axisY_labelFontSize = 66;
			
			// aapt resource value: 67
			public const int FlexChart_flexChart_axisY_labelFontTypeface = 67;
			
			// aapt resource value: 15
			public const int FlexChart_flexChart_axisY_labelFontWeight = 15;
			
			// aapt resource value: 17
			public const int FlexChart_flexChart_axisY_labelsVisible = 17;
			
			// aapt resource value: 72
			public const int FlexChart_flexChart_axisY_lineColor = 72;
			
			// aapt resource value: 73
			public const int FlexChart_flexChart_axisY_lineWidth = 73;
			
			// aapt resource value: 74
			public const int FlexChart_flexChart_axisY_majorGridColor = 74;
			
			// aapt resource value: 78
			public const int FlexChart_flexChart_axisY_majorGridFill = 78;
			
			// aapt resource value: 19
			public const int FlexChart_flexChart_axisY_majorGridVisible = 19;
			
			// aapt resource value: 75
			public const int FlexChart_flexChart_axisY_majorGridWidth = 75;
			
			// aapt resource value: 76
			public const int FlexChart_flexChart_axisY_majorTickColor = 76;
			
			// aapt resource value: 20
			public const int FlexChart_flexChart_axisY_majorTickOverlap = 20;
			
			// aapt resource value: 77
			public const int FlexChart_flexChart_axisY_majorTickWidth = 77;
			
			// aapt resource value: 79
			public const int FlexChart_flexChart_axisY_minorGridColor = 79;
			
			// aapt resource value: 83
			public const int FlexChart_flexChart_axisY_minorGridFill = 83;
			
			// aapt resource value: 21
			public const int FlexChart_flexChart_axisY_minorGridVisible = 21;
			
			// aapt resource value: 80
			public const int FlexChart_flexChart_axisY_minorGridWidth = 80;
			
			// aapt resource value: 81
			public const int FlexChart_flexChart_axisY_minorTickColor = 81;
			
			// aapt resource value: 22
			public const int FlexChart_flexChart_axisY_minorTickOverlap = 22;
			
			// aapt resource value: 82
			public const int FlexChart_flexChart_axisY_minorTickWidth = 82;
			
			// aapt resource value: 69
			public const int FlexChart_flexChart_axisY_titleFontColor = 69;
			
			// aapt resource value: 70
			public const int FlexChart_flexChart_axisY_titleFontSize = 70;
			
			// aapt resource value: 71
			public const int FlexChart_flexChart_axisY_titleFontTypeface = 71;
			
			// aapt resource value: 16
			public const int FlexChart_flexChart_axisY_titleFontWeight = 16;
			
			// aapt resource value: 32
			public const int FlexChart_flexChart_backgroundColor = 32;
			
			// aapt resource value: 33
			public const int FlexChart_flexChart_borderColor = 33;
			
			// aapt resource value: 34
			public const int FlexChart_flexChart_borderWidth = 34;
			
			// aapt resource value: 5
			public const int FlexChart_flexChart_chartType = 5;
			
			// aapt resource value: 28
			public const int FlexChart_flexChart_footer = 28;
			
			// aapt resource value: 31
			public const int FlexChart_flexChart_footerFontColor = 31;
			
			// aapt resource value: 3
			public const int FlexChart_flexChart_footerFontGravity = 3;
			
			// aapt resource value: 29
			public const int FlexChart_flexChart_footerFontSize = 29;
			
			// aapt resource value: 30
			public const int FlexChart_flexChart_footerFontTypeface = 30;
			
			// aapt resource value: 2
			public const int FlexChart_flexChart_footerFontWeight = 2;
			
			// aapt resource value: 24
			public const int FlexChart_flexChart_header = 24;
			
			// aapt resource value: 27
			public const int FlexChart_flexChart_headerFontColor = 27;
			
			// aapt resource value: 1
			public const int FlexChart_flexChart_headerFontGravity = 1;
			
			// aapt resource value: 25
			public const int FlexChart_flexChart_headerFontSize = 25;
			
			// aapt resource value: 26
			public const int FlexChart_flexChart_headerFontTypeface = 26;
			
			// aapt resource value: 0
			public const int FlexChart_flexChart_headerFontWeight = 0;
			
			// aapt resource value: 41
			public const int FlexChart_flexChart_legend_FontColor = 41;
			
			// aapt resource value: 42
			public const int FlexChart_flexChart_legend_FontSize = 42;
			
			// aapt resource value: 43
			public const int FlexChart_flexChart_legend_FontTypeface = 43;
			
			// aapt resource value: 4
			public const int FlexChart_flexChart_legend_FontWeight = 4;
			
			// aapt resource value: 38
			public const int FlexChart_flexChart_legend_backgroundColor = 38;
			
			// aapt resource value: 39
			public const int FlexChart_flexChart_legend_borderColor = 39;
			
			// aapt resource value: 40
			public const int FlexChart_flexChart_legend_borderWidth = 40;
			
			// aapt resource value: 23
			public const int FlexChart_flexChart_palette = 23;
			
			// aapt resource value: 35
			public const int FlexChart_flexChart_plotAreabackgroundColor = 35;
			
			// aapt resource value: 36
			public const int FlexChart_flexChart_selectedBorderColor = 36;
			
			// aapt resource value: 37
			public const int FlexChart_flexChart_selectedBorderWidth = 37;
			
			// aapt resource value: 6
			public const int FlexChart_flexChart_stackingType = 6;
			
			public static int[] Series = new int[] {
					2130771991,
					2130771992,
					2130772054,
					2130772055,
					2130772056,
					2130772057,
					2130772058,
					2130772059,
					2130772060,
					2130772061};
			
			// aapt resource value: 3
			public const int Series_flexChartSeries_binding = 3;
			
			// aapt resource value: 5
			public const int Series_flexChartSeries_borderColor = 5;
			
			// aapt resource value: 6
			public const int Series_flexChartSeries_borderWidth = 6;
			
			// aapt resource value: 0
			public const int Series_flexChartSeries_chartType = 0;
			
			// aapt resource value: 4
			public const int Series_flexChartSeries_color = 4;
			
			// aapt resource value: 2
			public const int Series_flexChartSeries_name = 2;
			
			// aapt resource value: 8
			public const int Series_flexChartSeries_symbolBorderColor = 8;
			
			// aapt resource value: 9
			public const int Series_flexChartSeries_symbolBorderWidth = 9;
			
			// aapt resource value: 7
			public const int Series_flexChartSeries_symbolColor = 7;
			
			// aapt resource value: 1
			public const int Series_flexChartSeries_visibility = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
